class AuthFailError(Exception):
    pass


class ResponseError(Exception):
    pass
